---
kate: hl yaml;
layout: null
---
backend:
  name: github
  repo: {{ site.repository }} # Path to your Github repository
  branch: master # Branch to update (master by default)
  base_url: https://cmsauth.beta-europe.org # Path to ext auth provider
{% raw %}
media_folder: "assets/images" # Folder where user uploaded files should go
logo_url: "https://www.beta-europe.org/assets/images/beta-logo-200-transparent.png"

collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "_posts" # The path to the folder where the documents are stored
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    meta: # Meta data fields. Just like fields, but without any preview element
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Post Excerpt (used in archive)", name: "excerpt", widget: "string"}
      - {label: "Link Type Post (leave empty for normal posts)", name: "link", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Categories", name: "categories", widget: "select", options: ["association", "network"], required: false}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mm:ss"}
      - {label: "Show Table of Contents", name: "toc", widget: "boolean", default: false, required: false}
      - {label: "Comments", name: "comments", widget: "boolean", default: false, required: false}
      - {label: "Social Share", name: "share", widget: "boolean", default: true, required: false}
      - {label: "Published", name: "published", widget: "boolean", default: true, required: false}
      - {label: "Show Edit Source", name: "edit", widget: "boolean", default: true, required: false}
      - label: "Cover Image"
        name: "header"
        widget: "object"
        required: false
        fields:
          - {label: "Image", name: "image", widget: "image", required: false}
          - {label: "Thumbnail for Image", name: "teaser", widget: "image", required: false}
          - {label: "Label (e.g. for credit)", name: "credit", widget: "string", required: false}
  - name: "pages"
    label: "Pages"
    folder: "_pages"
    slug: "{{slug}}"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1", required: true}
      - {label: "Modified Date", name: "modified", widget: "datetime", required: true}
      - {label: "Excerpt", name: "excerpt", widget: "string", reqired: false}
      - {label: "Show Table of Contents", name: "toc", widget: "boolean", default: false, required: false}
      - {label: "Social Share", name: "share", widget: "boolean", default: true, required: false}
      - {label: "Published", name: "published", widget: "boolean", default: true, required: false}
      - {label: "Show Edit Source", name: "edit", widget: "boolean", default: true, required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: "Cover Image"
        name: "header"
        widget: "object"
        required: false
        fields:
          - {label: "Image", name: "image", widget: "image", required: false}
          - {label: "Thumbnail for Image", name: "teaser", widget: "image", required: false}
          - {label: "Label (e.g. for credit)", name: "credit", widget: "string", required: false}
      - {label: "Show Author/Organisation Profile", name: "author_profile", widget: "boolean", required: false, default: true}
      - label: "Sidebar"
        name: "sidebar"
        widget: "object"
        required: false
        fields:
          - {label: "Title", name: "title", widget: "string", required: false}
          - {label: "Navigation Element", name: "nav", widget: "string", required: false}
          - {label: "Image", name: "image", widget: "image", required: false}
          - {label: "Image Description", name: "image_alt", widget: "string", required: false}
          - {label: "Text", name: "text", widget: "markdown", required: false}
  - name: "partner"
    label: "Partner"
    folder: "_partners"
    sort: "title:asc"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Slug", name: "slug", widget: "string", required: true}
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Website (e.g. http://meu.eu)", name: "website", widget: "string"}
      - {label: "Twitter Handle (without at)", name: "twitter", widget: "string", required: false}
      - {label: "Mail", name: "mail", widget: "string", required: false}
      - {label: "Linkedin (e.g. http://linkedin.com/BETAEU)", name: "linkedin", widget: "string", required: false}
      - {label: "Instagram (e.g. BetaEU)", name: "instagram", widget: "string", required: false}
      - {label: "Facebook (e.g. http://facebook.com/betaEU)", name: "facebook", widget: "string", required: false}
      - {label: "Excerpt (used in Partner Overview)", name: "excerpt", widget: "string", required: false}
      - {label: "President", name: "president", widget: "string", required: false}
      - {label: "Country", name: "country", widget: "string", required: false}
      - {label: "Town", name: "town", widget: "string", required: false}
      - {label: "Location", name: "location", widget: "string", required: false}
      - {label: "Members", name: "members", widget: "string", required: false}
      - {label: "Geo Location (e.g.: 52.2333,20.8891)", name: "geo", widget: "string", required: false}
      # - {label: "conferences", name: "conferences", widget: "relation", collection: "conference", searchFields: ["conference"], valueField: "conference"}
      - {label: "Partner Description", name: "body", widget: "markdown", required: false}
      - label: "Cover Image"
        name: "header"
        widget: "object"
        required: false
        fields:
          - {label: "Image", name: "image", widget: "image", required: false}
          - {label: "Thumbnail for Partner Overview", name: "teaser", widget: "image", required: false}
          - {label: "Label (e.g. for credit)", name: "credit", widget: "string", required: false}
{% endraw %}{% if site.cms.has_members %}{% raw %}
  - name: "member"
    label: "Members"
    folder: "_members"
    sort: "title:asc"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Slug", name: "slug", widget: "string", required: true}
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Website (e.g. http://meu.eu)", name: "website", widget: "string"}
      - {label: "Twitter Handle (without at)", name: "twitter", widget: "string", required: false}
      - {label: "Mail", name: "mail", widget: "string", required: false}
      - {label: "Linkedin (e.g. http://linkedin.com/BETAEU)", name: "linkedin", widget: "string", required: false}
      - {label: "Instagram (e.g. BetaEU)", name: "instagram", widget: "string", required: false}
      - {label: "Facebook (e.g. http://facebook.com/betaEU)", name: "facebook", widget: "string", required: false}
      - {label: "Excerpt (used in Partner Overview)", name: "excerpt", widget: "string", required: false}
      - {label: "President", name: "president", widget: "string", required: false}
      - {label: "Country", name: "country", widget: "string", required: false}
      - {label: "Town", name: "town", widget: "string", required: false}
      - {label: "Location", name: "location", widget: "string", required: false}
      - {label: "Members (in Member association)", name: "members", widget: "string", required: false}
      - {label: "Geo Location (e.g.: 52.2333,20.8891)", name: "geo", widget: "string", required: false}
      # - {label: "conferences", name: "conferences", widget: "relation", collection: "conference", searchFields: ["conference"], valueField: "conference"}
      - {label: "Member Description", name: "body", widget: "markdown", required: false}
      - label: "Cover Image"
        name: "header"
        widget: "object"
        required: false
        fields:
          - {label: "Image", name: "image", widget: "image", required: false}
          - {label: "Thumbnail for Member Overview", name: "teaser", widget: "image", required: false}
          - {label: "Label (e.g. for credit)", name: "credit", widget: "string", required: false}
{% endraw %}{% endif %}{% if site.cms.has_observers %}{% raw %}
  - name: "observer"
    label: "Observers"
    folder: "_observers"
    sort: "title:asc"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Slug", name: "slug", widget: "string", required: true}
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Website (e.g. http://meu.eu)", name: "website", widget: "string"}
      - {label: "Twitter Handle (without at)", name: "twitter", widget: "string", required: false}
      - {label: "Mail", name: "mail", widget: "string", required: false}
      - {label: "Linkedin (e.g. http://linkedin.com/BETAEU)", name: "linkedin", widget: "string", required: false}
      - {label: "Instagram (e.g. BetaEU)", name: "instagram", widget: "string", required: false}
      - {label: "Facebook (e.g. http://facebook.com/betaEU)", name: "facebook", widget: "string", required: false}
      - {label: "Excerpt (used in Partner Overview)", name: "excerpt", widget: "string", required: false}
      - {label: "President", name: "president", widget: "string", required: false}
      - {label: "Country", name: "country", widget: "string", required: false}
      - {label: "Town", name: "town", widget: "string", required: false}
      - {label: "Location", name: "location", widget: "string", required: false}
      - {label: "Members (in Member association)", name: "members", widget: "string", required: false}
      - {label: "Geo Location (e.g.: 52.2333,20.8891)", name: "geo", widget: "string", required: false}
      # - {label: "conferences", name: "conferences", widget: "relation", collection: "conference", searchFields: ["conference"], valueField: "conference"}
      - {label: "Member Description", name: "body", widget: "markdown", required: false}
      - label: "Cover Image"
        name: "header"
        widget: "object"
        required: false
        fields:
          - {label: "Image", name: "image", widget: "image", required: false}
          - {label: "Thumbnail for Member Overview", name: "teaser", widget: "image", required: false}
          - {label: "Label (e.g. for credit)", name: "credit", widget: "string", required: false}
{% endraw %}{% endif %}{% if site.cms.has_conference %}{% raw %}
  - name: "conference"
    label: "Conference"
    folder: "_conferences"
    sort: "title:asc"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title (e.g. MEU Strasbourg 2015)", name: "title", widget: "string", required: true}
      - {label: "Slug (e.g. meu-strasbourg-2015)", name: "slug", widget: "string", required: true}
      - {label: "Partner Slug (e.g. beta-france)", name: "partner-slug", widget: "relation", collection: "partner", searchFields: ["title"], valueField: "slug", required: false}
      - {label: "Conference Series (e.g. meu-strasbourg)", name: "conference", widget: "string", required: true}
      - {label: "Year", name: "year", widget: "number", valueType: "int", required: true, pattern: ['\d{4}', "Provide conference year."], default: 2018}
      - {label: "Conference Start", name: "begin", widget: "date", format: "YYYY-MM-DD", required: true}
      - {label: "Conference End", name: "end", widget: "date", format: "YYYY-MM-DD", required: true}
      - {label: "Mail", name: "mail", widget: "string", required: false}
      - {label: "Website (e.g. http://mywebsite.eu)", name: "website", widget: "string", required: true}
      - {label: "Twitter Handle (without at)", name: "twitter", widget: "string", required: false, pattern: ['[A-Za-z0-9_]{1,20}', "Provide Twitter handle without @."]}
      - {label: "Country", name: "country", widget: "string", required: false}
      - {label: "Town", name: "town", widget: "string", required: false}
      - {label: "Location", name: "location", widget: "string", required: false}
      - {label: "Participant Number", name: "participants", widget: "string", required: false}
      - {label: "Geo Location (e.g.: 52.2333,20.8891)", name: "geo", widget: "string", required: false}
      - {label: "Topic Excerpt (used in archive)", name: "excerpt", widget: "string", required: false}
      - {label: "Conference Description", name: "body", widget: "markdown", required: false}
      - label: "Cover Image"
        name: "header"
        widget: "object"
        required: false
        fields:
          - {label: "Image", name: "image", widget: "image", required: false}
          - {label: "Thumbnail for Image", name: "teaser", widget: "image", required: false}
          - {label: "Label (e.g. for credit)", name: "credit", widget: "string", required: false}
{% endraw %}{% endif %}{% raw %}
  - name: "teammember" # Used in routes, ie.: /admin/collections/:slug/edit
    Label: "TeamMembers" # Used in the UI, ie.: "New Post"
    folder: "_teammembers" # The path to the folder where the documents are stored
    sort: "title:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Name", name: "name", widget: "string", required: true}
      - {label: "Title" name: "title", widget: "string", required: true}
      - {label: "Mail", name: "mail", widget: "string"}
      - label: "Cover Image"
        name: "header"
        widget: "object"
        required: false
        fields:
          - {label: "Image", name: "image", widget: "image", required: false}
          - {label: "Thumbnail for Image", name: "teaser", widget: "image", required: false}
          - {label: "Label (e.g. for credit)", name: "credit", widget: "string", required: false}
{% endraw %}{% endif %}{% raw %}
  - name: "settings"
    label: "Settings"
    files:
      - name: "navigations"
        label: "Navigations"
        file: "_data/navigation.yml"
        fields:
          - name: "main"
            label: "Main Navigation"
            widget: list
            fields:
              - name: title
                label: "Label"
                widget: string
              - name: url
                label: "URL (e.g. /about/ or https://twitter.com)"
                widget: string
          - name: "teams"
            label: "Teams Sidebar"
            widget: list
            fields:
              - name: title
                label: "Team Label"
                widget: string
              - name: children
                label: "Navigation Elements"
                widget: list
                fields:
                  - name: title
                    label: "Label"
                    widget: string
                  - name: url
                    label: "URL (e.g. /about/ or https://twitter.com)"
                    widget: string
{% endraw %}
